networks:
  spark-net:
    driver: bridge

services:
  spark-master:
    build: ./spark-image
    image: custom-spark:4.0.2
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./app:/opt/spark-app
      - ./data:/opt/spark-data
    networks:
      - spark-net

  spark-worker-1:
    image: custom-spark:4.0.2
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_NO_DAEMONIZE=true
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "8081:8081"
    depends_on:
      spark-master:
        condition: service_started
    volumes:
      - ./app:/opt/spark-app
      - ./data:/opt/spark-data
    networks:
      - spark-net

  spark-worker-2:
    image: custom-spark:4.0.2
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_NO_DAEMONIZE=true
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "8082:8081"
    depends_on:
      spark-master:
        condition: service_started
    volumes:
      - ./app:/opt/spark-app
      - ./data:/opt/spark-data
    networks:
      - spark-net

  jupyter:
    build: ./jupyter-image
    image: custom-jupyter:4.0.2
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
      - JAVA_TOOL_OPTIONS=-Xmx3g
    deploy:
      resources:
        limits:
          memory: 4g
    depends_on:
      spark-master:
        condition: service_started
    volumes:
      - ./app:/opt/spark-app
      - ./data:/opt/spark-data
      - ./notebooks:/opt/spark-notebooks
    networks:
      - spark-net